### ISSUE TITLE
Define the 6 views

### ISSUE THREAD

**Issue by DanielOsorio01** [ISIS3510-202320-Team22/Wiki#4]

**Comment by DanielOsorio01** [comment]
As provided by my Teammate Calixto, the selected views are:
- Home
- Login
- Settings
- Publish post
- Take a photo
- Search by category

These views are being detailed in [Figma](https://www.figma.com/file/18EgEOjxvS2iwT9jqf1EPo/Guarap?type=design&node-id=0-1&mode=design)

**Comment by jngm8** [comment]
I think home view in an app is unnecessary, because when a user enters the app what he should see first is the feed (published photos from other users and a navigation bar with options within the same view), therefore a home is more suitable for a webpage where you can see the menu options and start from there.

Here is what we have to take into account for the views of the sprint 2
![image](https://github.com/ISIS3510-202320-Team22/Wiki/assets/68575075/ff04e2e2-604e-4c81-a247-d4313fde2042)

**Comment by DanielOsorio01** [comment]
I think those functionalities are important, but not all of those are needed for defining the views for this microsprint. I would suggest a new issue for that topic.

**Comment by DanielOsorio01** [comment]
I think those functionalities are important, but not all of those are needed for defining the views for this microsprint. I would suggest a new issue for that topic.

**Comment by DanielOsorio01** [comment]
I think the last view (search by category) is a functionality instead of a feature. I would change this for a profile screen

**Comment by jcalixto202020774** [comment]
https://github.com/ISIS3510-202320-Team22/Wiki/wiki/MS7/62110722339fd8f7016df440d8be36c97edc8655
